Repository Debaditya-Som/Data-Visualization-in-Python, pull requests merged in 2023-10, with the labels that each got.

#6 Update Bar.py
  Bar.py
Labels: enhancement, hacktoberfest-accepted

#7 Update Histogram.py
  Histogram.py
Labels: enhancement, hacktoberfest-accepted

#10 Added beginner program on matplotlib
  001_getting_started.py
Labels: enhancement, hacktoberfest-accepted

#13 added basic python code folder and included a tictactoe game
  PythonCodes/TicTacToe.py
Labels: enhancement, hacktoberfest-accepted

#12 Update PieChart.py
  PieChart.py
Labels: enhancement, hacktoberfest-accepted

#11 Create scatter.py
  scatter.py
Labels: enhancement, hacktoberfest-accepted

#15 Update VISUALIZATION.md
  VISUALIZATION.md
Labels: enhancement, hacktoberfest-accepted

#21 Create scatterplot.py
  Visualization Codes/scatterplot.py
Labels: enhancement, hacktoberfest-accepted

#24 Password Strength checker by Python
  PythonCodes/PasswordStrengthChecker.py
Labels: enhancement, hacktoberfest-accepted

#26 Added Perceptron Trick
  PythonCodes/Perceptron Trick.ipynb
Labels: enhancement, hacktoberfest-accepted

#29 added CONTRIBUTIONS.md file
  CONTRIBUTIONS.md
Labels: documentation, hacktoberfest-accepted

#30 Added Ridge Regression
  PythonCodes/Ridge Regresion.ipynb
Labels: enhancement, hacktoberfest-accepted

#31 Create stopwatchGUI.py
  PythonCodes/stopwatchGUI.py
Labels: enhancement, hacktoberfest-accepted

#39 Added SVM Kernel Trick
  PythonCodes/SVM Kernel Trick.ipynb
Labels: hacktoberfest-accepted

#38 Create OTPverification.py
  PythonCodes/OTPverification.py
Labels: hacktoberfest-accepted

#37 Update Figure.py
  Visualization Codes/Figure.py
Labels: hacktoberfest-accepted

#32 Histogram Equalisation Technique
  Visualization Codes/enhance.jpg
  Visualization Codes/enhance_histogram.py
  output_plots/Histogram equalisation.png
  output_plots/result.jpg
Labels: hacktoberfest-accepted

#49 Create basic.py
  PythonCodes/basic.py
Labels: hacktoberfest-accepted
